/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-28 11:59:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainJSP_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1532767410426L));
    _jspx_dependants.put("jar:file:/D:/rentacar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/rentacarWEB/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Main</title>\r\n");
      out.write("<style>\r\n");
      out.write(".view {\r\n");
      out.write("\tbackground:\r\n");
      out.write("\t\turl(\"https://mdbootstrap.com/img/Photos/Others/img (40).jpg\")\r\n");
      out.write("\t\tno-repeat center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-nav-collapse {\r\n");
      out.write("\tbackground-color: #4285F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (max-width: 768px) {\r\n");
      out.write("\t.navbar {\r\n");
      out.write("\t\tbackground-color: #4285F4;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header> <nav\r\n");
      out.write("\t\tclass=\"navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar\">\r\n");
      out.write("\t<a class=\"navbar-brand\" href=\"#\"><strong>Navbar</strong></a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<form class=\"navbar-nav mr-auto\" action=\"/rentacarWEB/KontaktServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t<button  type=\"submit\" class=\"button\">Kontakt</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form class=\"navbar-nav mr-auto\" action=\"/rentacarWEB/ListaAutomobilaServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t<button  type=\"submit\" class=\"button\">Automobili</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form class=\"navbar-nav mr-auto\" action=\"/rentacarWEB/LoginServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t<button  type=\"submit\" class=\"button\">Login</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"view intro hm-purple-light\" style=\"height: 400px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--Main Navigation-->\r\n");
      out.write("\r\n");
      out.write("\t<!--Main Layout-->\r\n");
      out.write("\t<main class=\"text-center py-5\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p align=\"justify\">Europcar Rent a Car Beograd, Novi Sad, Niš\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tNajpovoljnije ponude rent a car usluga u Beogradu,Novom Sadu i\r\n");
      out.write("\t\t\t\t\tNišu, stabilnost cena, specijalne ponude prema potrebama klijenata,\r\n");
      out.write("\t\t\t\t\tnajnoviji modeli vozila, najveći spektar dizel i automatik vozila,\r\n");
      out.write("\t\t\t\t\tnajmlađa vozila na tržištu, Europcar kao Vaš pouzdan partner.\r\n");
      out.write("\t\t\t\t\tMožete se osloniti na nas. Da li se radi o dnevnom najmu u zemlji\r\n");
      out.write("\t\t\t\t\tili inostranstvu, prelaznom rešenju na nekoliko meseci ili kupovini\r\n");
      out.write("\t\t\t\t\tvozila na duži period, Europcar vaš prati kao Vaš pouzdani partner.\r\n");
      out.write("\t\t\t\t\tSa našom flotom od 55 grupa vozila, od najmanjeg gradskog vozila,\r\n");
      out.write("\t\t\t\t\tpreko poslovnih limuzina i 4x4 džipova, pa do komercijalnih vozila,\r\n");
      out.write("\t\t\t\t\tEuropcar je tu da za Vas obezbedi najbolju soluciju. Kretanje kroz\r\n");
      out.write("\t\t\t\t\tBeograd nikad nije bilo lakše i jeftnije nego sad uz Europcar rent\r\n");
      out.write("\t\t\t\t\ta car vozila na Beogradskom Aerodromu. Čim stignete na aerodrom\r\n");
      out.write("\t\t\t\t\tBeograd preuzmete rent a car vozilo, možete krenuti u istraživanje\r\n");
      out.write("\t\t\t\t\tprelepih predela</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!--Main Layout-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
